#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
